#!/usr/bin/env bash
# Install nginx on your web-01
#prin hello world into index file
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
service nginx start
