#!/usr/bin/env bash
# Install nginx on your web-01
#prin hello world into index file
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World" > /var/www/html/index.html
service nginx start
