#!/usr/bin/env bash
# Configure your Nginx server so that 
# /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com p:wqermanent;/" /etc/nginx/sites-available/default
service nginx start
