#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
n=1
while [ $n -le 20 ];
do
    if [ $n -eq 4 ]
    then
        echo "bad luck from China";
    elif [ $n -eq 9 ]
    then
        echo "bad luck fron Japan";
    elif [ $n -eq 17 ]
    then
        echo "bad luck from Italy"
    else
        echo "$n"
    fi;
    n=$((n + 1));
done;
